version: "2"
services:
  nginx:
    build:
      context: ./nginx
    ports:
    - "8080:80"
    - "443:443"
    volumes:
    - /tmp/xcellerate:/mnt
    links:
    - fpm
  fpm:
      build:
          context: ./fpm